// Every dashboard view; the shell switches between them in place.
export type DashboardTab =
  | "home"
  | "skills"
  | "characters"
  | "command-center"
  | "activity"
  | "approvals"
  | "vault"
  | "trusted"
  | "email"
  | "integrations"
  | "memory"
  | "schedules"
  | "conversation"
  | "history"
  | "status"
  | "billing"
  | "profile"
  | "writing-style"
  | "privacy"
  | "referrals"
  | "streaks"
