import { mkdirSync, writeFileSync } from "node:fs"
import { join, dirname } from "node:path"
import type { CertificationReport, SuiteResult, CertificationStatus } from "./types.js"

export function generateReport(
  suites: SuiteResult[],
  phase = "Phase X1 — Universal Application Certification",
  reportDir?: string,
): CertificationReport {
  const total = suites.length
  const certified = suites.filter((s) => s.status === "certified").length
  const notVerified = suites.filter((s) => s.status === "not_verified").length
  const degraded = suites.filter((s) => s.status === "degraded").length
  const failing = suites.filter((s) => s.status === "failing").length
  const pending = suites.filter((s) => s.status === "pending").length

  const allTests = suites.flatMap((s) => s.tests)
  const tested = allTests.filter((t) => t.status !== "skip" && t.status !== "error")
  const passed = allTests.filter((t) => t.status === "pass").length
  const overallRate = tested.length > 0 ? Math.round((passed / tested.length) * 100) : 0

  const report: CertificationReport = {
    phase,
    generatedAt: new Date().toISOString(),
    platform: process.platform,
    hostname: process.env.COMPUTERNAME || "unknown",
    suites,
    summary: {
      total,
      certified,
      notVerified,
      degraded,
      failing,
      pending,
      overallRate,
    },
  }

  if (reportDir) {
    mkdirSync(reportDir, { recursive: true })
    const jsonPath = join(reportDir, "certification-report.json")
    writeFileSync(jsonPath, JSON.stringify(report, null, 2), "utf8")

    const mdPath = join(reportDir, "certification-report.md")
    writeFileSync(mdPath, renderMarkdown(report), "utf8")

    const htmlPath = join(reportDir, "certification-report.html")
    writeFileSync(htmlPath, renderHtml(report), "utf8")
  }

  return report
}

function statusBadge(status: CertificationStatus): string {
  const colors: Record<CertificationStatus, string> = {
    certified: "green",
    not_verified: "red",
    degraded: "yellow",
    failing: "red",
    pending: "gray",
    skipped: "gray",
  }
  return `![${status}](https://img.shields.io/badge/${status}-${colors[status]})`
}

function renderMarkdown(report: CertificationReport): string {
  const lines: string[] = [
    `# ${report.phase}`,
    ``,
    `**Generated:** ${report.generatedAt}`,
    `**Platform:** ${report.platform}`,
    `**Host:** ${report.hostname}`,
    ``,
    `## Summary`,
    ``,
    `| Metric | Value |`,
    `| --- | --- |`,
    `| Total Suites | ${report.summary.total} |`,
    `| Certified | ${report.summary.certified} |`,
    `| Not Verified | ${report.summary.notVerified} |`,
    `| Degraded | ${report.summary.degraded} |`,
    `| Failing | ${report.summary.failing} |`,
    `| Pending | ${report.summary.pending} |`,
    `| Overall Success Rate | ${report.summary.overallRate}% |`,
    ``,
    `## Suite Results`,
    ``,
    `| App | Category | Status | Passed | Total | Rate | Duration |`,
    `| --- | --- | --- | ---: | ---: | ---: | ---: |`,
  ]

  for (const suite of report.suites) {
    const rate = suite.summary.total > 0
      ? Math.round((suite.summary.passed / suite.summary.total) * 100)
      : 0
    lines.push(
      `| ${suite.app} | ${suite.category} | ${suite.status} | ${suite.summary.passed}/${suite.summary.total} | ${suite.summary.total} | ${rate}% | ${suite.duration}ms |`,
    )
  }

  lines.push(``, `## Test Details`, ``)

  for (const suite of report.suites) {
    lines.push(`### ${suite.app} (${suite.status})`, ``)
    lines.push(`| # | Test | Status | Duration | Error |`, `| --- | --- | --- | ---: | --- |`)
    for (const test of suite.tests) {
      lines.push(
        `| ${test.id} | ${test.name} | ${test.status} | ${test.duration}ms | ${test.error ?? ""} |`,
      )
    }
    lines.push(``)
  }

  lines.push(`---`, `*Report generated by Yomi Certification Framework*`)
  return lines.join("\n")
}

function renderHtml(report: CertificationReport): string {
  const statusColor = (s: CertificationStatus) => {
    const map: Record<CertificationStatus, string> = {
      certified: "#22c55e",
      not_verified: "#ef4444",
      degraded: "#eab308",
      failing: "#dc2626",
      pending: "#9ca3af",
      skipped: "#9ca3af",
    }
    return map[s]
  }

  const suiteRows = report.suites.map((s) => {
    const rate = s.summary.total > 0
      ? Math.round((s.summary.passed / s.summary.total) * 100)
      : 0
    return `<tr>
      <td>${s.app}</td>
      <td>${s.category}</td>
      <td><span style="color:${statusColor(s.status)};font-weight:bold">${s.status}</span></td>
      <td>${s.summary.passed}/${s.summary.total}</td>
      <td>${rate}%</td>
      <td>${s.duration}ms</td>
    </tr>`
  }).join("\n")

  const detailSections = report.suites.map((s) => {
    const testRows = s.tests.map((t) => `<tr>
      <td>${t.id}</td>
      <td>${t.name}</td>
      <td style="color:${t.status === "pass" ? "#22c55e" : "#ef4444"}">${t.status}</td>
      <td>${t.duration}ms</td>
      <td>${t.error ?? ""}</td>
    </tr>`).join("\n")
    return `<h3 style="color:${statusColor(s.status)}">${s.app} (${s.status})</h3>
      <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%">
        <tr style="background:#f0f0f0"><th>#</th><th>Test</th><th>Status</th><th>Duration</th><th>Error</th></tr>
        ${testRows}
      </table>`
  }).join("\n<br>\n")

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${report.phase}</title>
  <style>
    body { font-family: -apple-system, sans-serif; max-width: 1200px; margin: 0 auto; padding: 2rem; background: #1a1a2e; color: #e0e0e0; }
    h1 { color: #7c3aed; border-bottom: 2px solid #7c3aed; padding-bottom: 0.5rem; }
    h2 { color: #a78bfa; }
    table { border: 1px solid #333; }
    th { background: #2d2d44; }
    td, th { padding: 6px 12px; border: 1px solid #333; }
    .certified { color: #22c55e; }
    .summary-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 1rem; margin: 1rem 0; }
    .stat-card { background: #2d2d44; padding: 1rem; border-radius: 8px; text-align: center; }
    .stat-value { font-size: 2rem; font-weight: bold; }
    .stat-label { font-size: 0.85rem; color: #9ca3af; }
  </style>
</head>
<body>
  <h1>${report.phase}</h1>
  <p><strong>Generated:</strong> ${report.generatedAt} &bull; <strong>Platform:</strong> ${report.platform} &bull; <strong>Host:</strong> ${report.hostname}</p>

  <h2>Summary</h2>
  <div class="summary-grid">
    <div class="stat-card"><div class="stat-value">${report.summary.total}</div><div class="stat-label">Total Suites</div></div>
    <div class="stat-card"><div class="stat-value" style="color:#22c55e">${report.summary.certified}</div><div class="stat-label">Certified</div></div>
    <div class="stat-card"><div class="stat-value" style="color:#ef4444">${report.summary.notVerified}</div><div class="stat-label">Not Verified</div></div>
    <div class="stat-card"><div class="stat-value" style="color:#eab308">${report.summary.degraded}</div><div class="stat-label">Degraded</div></div>
    <div class="stat-card"><div class="stat-value" style="color:#dc2626">${report.summary.failing}</div><div class="stat-label">Failing</div></div>
    <div class="stat-card"><div class="stat-value" style="color:#9ca3af">${report.summary.pending}</div><div class="stat-label">Pending</div></div>
    <div class="stat-card"><div class="stat-value">${report.summary.overallRate}%</div><div class="stat-label">Overall Rate</div></div>
  </div>

  <h2>Suite Results</h2>
  <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%">
    <tr style="background:#2d2d44"><th>App</th><th>Category</th><th>Status</th><th>Passed/Total</th><th>Rate</th><th>Duration</th></tr>
    ${suiteRows}
  </table>

  <h2>Test Details</h2>
  ${detailSections}

  <hr>
  <p style="color:#9ca3af;font-size:0.85rem">Report generated by Yomi Certification Framework</p>
</body>
</html>`
}
